{"name": "Test - Validar la creaci√≥n de un Intermediario", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=45203): Max retries exceeded with url: /session/1071cd959610a7923278f577da3c608a/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79d9f3092610>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/behave/runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features/environment.py\", line 56, in after_step\n    pm.hook.after_step(context=context, step=step)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 60, in _multicall\n    return outcome.get_result()\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ipadula/Avla/helper/plugins/SeleniumPlugin.py\", line 187, in after_step\n    allure.attach(context.browser.get_screenshot_as_png(), name=\"screenshot\", attachment_type=AttachmentType.PNG)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 927, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 938, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 438, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/request.py\", line 74, in request\n    return self.request_encode_url(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/request.py\", line 96, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 785, in urlopen\n    retries = retries.increment(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "steps": [{"name": "Given Estoy en el ingreso al portal sin loguearme", "status": "passed", "attachments": [{"name": "screenshot", "source": "76d4fdfa-f105-4219-ae4f-234c45826d01-attachment.png", "type": "image/png"}], "start": 1749775965307, "stop": 1749775969258}, {"name": "When Me logueo con las credenciales \"admin\"", "status": "passed", "attachments": [{"name": "screenshot", "source": "61ea66d0-8058-4477-a73d-326db281a050-attachment.png", "type": "image/png"}], "start": 1749775969258, "stop": 1749775975944}, {"name": "And Despliego la seccion \"Maintenance\"", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=45203): Max retries exceeded with url: /session/1071cd959610a7923278f577da3c608a/screenshot (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79d9f3092610>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "trace": "  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/behave/runner.py\", line 545, in run_hook\n    self.hooks[name](context, *args)\n  File \"features/environment.py\", line 56, in after_step\n    pm.hook.after_step(context=context, step=step)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 60, in _multicall\n    return outcome.get_result()\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ipadula/Avla/helper/plugins/SeleniumPlugin.py\", line 187, in after_step\n    allure.attach(context.browser.get_screenshot_as_png(), name=\"screenshot\", attachment_type=AttachmentType.PNG)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 927, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 938, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 438, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py\", line 290, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py\", line 311, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/request.py\", line 74, in request\n    return self.request_encode_url(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/request.py\", line 96, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 785, in urlopen\n    retries = retries.increment(\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1749775975945, "stop": 1749775982066}, {"name": "And Me dirijo a la seccion \"Brokers\"", "status": "skipped", "start": 1749775982118, "stop": 1749775982118}, {"name": "And Presiono el boton \"New\"", "status": "skipped", "start": 1749775982118, "stop": 1749775982118}, {"name": "And Selecciono en \"ID Type\" \"SSN\" en \"General data\"", "status": "skipped", "start": 1749775982118, "stop": 1749775982118}, {"name": "And Agrego un \"Name\" \"a\" en \"General data\"", "status": "skipped", "start": 1749775982118, "stop": 1749775982118}, {"name": "And Agrego un \"Phone Number\" \"a\" en \"General data\"", "status": "skipped", "start": 1749775982118, "stop": 1749775982118}, {"name": "And Agrego un \"Email\" \"a\" en \"General data\"", "status": "skipped", "start": 1749775982118, "stop": 1749775982118}, {"name": "And Agrego un \"Agency License Number\" \"a\" en \"General data\"", "status": "skipped", "start": 1749775982118, "stop": 1749775982118}, {"name": "And Agrego un \"ID Number\" \"a\" en \"General data\"", "status": "skipped", "start": 1749775982118, "stop": 1749775982118}, {"name": "And Selecciono en \"Legal Person Type\" \"Individual / Sole proprietorship\" en \"General data\"", "status": "skipped", "start": 1749775982118, "stop": 1749775982118}, {"name": "And Seteo \"Expiration\" en \"12/12/2030\" en \"General data\"", "status": "skipped", "start": 1749775982118, "stop": 1749775982118}, {"name": "And Presiono el boton \"Add\"", "status": "skipped", "start": 1749775982118, "stop": 1749775982118}, {"name": "And Agrego un \"Range\" \"50\" en \"General data\"", "status": "skipped", "start": 1749775982118, "stop": 1749775982118}, {"name": "And Presiono el boton \"Request range\"", "status": "skipped", "start": 1749775982118, "stop": 1749775982118}, {"name": "And Presiono \"Alaska\" en \"Agency Licenses\"", "status": "skipped", "start": 1749775982118, "stop": 1749775982118}, {"name": "And Selecciono \"Physical\" en \"General data\"", "status": "skipped", "start": 1749775982118, "stop": 1749775982118}, {"name": "And Agrego un \"Address Number\" \"a\" en \"General data\"", "status": "skipped", "start": 1749775982119, "stop": 1749775982119}, {"name": "And Agrego un \"Street Name\" \"a\" en \"General data\"", "status": "skipped", "start": 1749775982119, "stop": 1749775982119}, {"name": "And Agrego un \"ZIP Code\" \"a\" en \"General data\"", "status": "skipped", "start": 1749775982119, "stop": 1749775982119}, {"name": "And Selecciono en \"State\" \"Arkansas\" en \"General data\"", "status": "skipped", "start": 1749775982119, "stop": 1749775982119}, {"name": "And Selecciono en \"City\" \"ALLEENE\" en \"General data\"", "status": "skipped", "start": 1749775982119, "stop": 1749775982119}, {"name": "And Presiono \"Add\"", "status": "skipped", "start": 1749775982119, "stop": 1749775982119}, {"name": "And Presiono \"Save\"", "status": "skipped", "start": 1749775982119, "stop": 1749775982119}, {"name": "And Presiono \"Yes\"", "status": "skipped", "start": 1749775982119, "stop": 1749775982119}, {"name": "And Me dirijo a la seccion \"Brokers\"", "status": "skipped", "start": 1749775982119, "stop": 1749775982119}, {"name": "And Selecciono \"SSN\"", "status": "skipped", "start": 1749775982119, "stop": 1749775982119}, {"name": "And Agrego un \"ID Number\"", "status": "skipped", "start": 1749775982119, "stop": 1749775982119}, {"name": "And Presiono el boton para buscar", "status": "skipped", "start": 1749775982119, "stop": 1749775982119}, {"name": "Then Valido que exista un resultado", "status": "skipped", "start": 1749775982119, "stop": 1749775982119}], "start": 1749775963188, "stop": 1749775982136, "uuid": "1b119de4-5be5-4ec0-b050-e51da8b1242c", "historyId": "9ebdac3eb2c2c38d87424bb39876ba3d", "fullName": "Maintenance: Test - Validar la creaci√≥n de un Intermediario", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "brokers"}, {"name": "tag", "value": "maintenance"}, {"name": "tag", "value": "regresion"}, {"name": "feature", "value": "Maintenance"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}