{"name": "Test - Validar la creaci贸n de un grupo econ贸mico", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable\n  (Session info: chrome=137.0.7151.68)\nStacktrace:\n#0 0x5b8d265e37fa <unknown>\n#1 0x5b8d26087ce3 <unknown>\n#2 0x5b8d260daa7e <unknown>\n#3 0x5b8d260cd97d <unknown>\n#4 0x5b8d260ff242 <unknown>\n#5 0x5b8d260cd2fa <unknown>\n#6 0x5b8d260ff40e <unknown>\n#7 0x5b8d26125135 <unknown>\n#8 0x5b8d260ff013 <unknown>\n#9 0x5b8d260cbb3b <unknown>\n#10 0x5b8d260cc7a1 <unknown>\n#11 0x5b8d265a8b9b <unknown>\n#12 0x5b8d265aca8a <unknown>\n#13 0x5b8d26590912 <unknown>\n#14 0x5b8d265ad604 <unknown>\n#15 0x5b8d2657574f <unknown>\n#16 0x5b8d265d1678 <unknown>\n#17 0x5b8d265d1856 <unknown>\n#18 0x5b8d265e2666 <unknown>\n#19 0x7f4e2829caa4 <unknown>\n#20 0x7f4e28329c3c <unknown>\n\n", "trace": "  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/WhenDefinition.py\", line 40, in step_impl\n    context.elements._implicity_wait(int(os.getenv(\"IMPLICITY_WAIT\")),\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py\", line 94, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py\", line 404, in _execute\n    return self._parent.execute(command, params)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Estoy en el ingreso al portal sin loguearme", "status": "passed", "attachments": [{"name": "screenshot", "source": "c10f847e-a79f-4ba2-b67e-f74f1ae7dc82-attachment.png", "type": "image/png"}], "start": 1750275086424, "stop": 1750275090477}, {"name": "When Me logueo con las credenciales \"admin\"", "status": "passed", "attachments": [{"name": "screenshot", "source": "eb431d44-9baf-46ad-8b0e-46685fa1cb64-attachment.png", "type": "image/png"}], "start": 1750275090477, "stop": 1750275096775}, {"name": "And Despliego la seccion \"Risk Management\"", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable\n  (Session info: chrome=137.0.7151.68)\nStacktrace:\n#0 0x5b8d265e37fa <unknown>\n#1 0x5b8d26087ce3 <unknown>\n#2 0x5b8d260daa7e <unknown>\n#3 0x5b8d260cd97d <unknown>\n#4 0x5b8d260ff242 <unknown>\n#5 0x5b8d260cd2fa <unknown>\n#6 0x5b8d260ff40e <unknown>\n#7 0x5b8d26125135 <unknown>\n#8 0x5b8d260ff013 <unknown>\n#9 0x5b8d260cbb3b <unknown>\n#10 0x5b8d260cc7a1 <unknown>\n#11 0x5b8d265a8b9b <unknown>\n#12 0x5b8d265aca8a <unknown>\n#13 0x5b8d26590912 <unknown>\n#14 0x5b8d265ad604 <unknown>\n#15 0x5b8d2657574f <unknown>\n#16 0x5b8d265d1678 <unknown>\n#17 0x5b8d265d1856 <unknown>\n#18 0x5b8d265e2666 <unknown>\n#19 0x7f4e2829caa4 <unknown>\n#20 0x7f4e28329c3c <unknown>\n\n", "trace": "  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/WhenDefinition.py\", line 40, in step_impl\n    context.elements._implicity_wait(int(os.getenv(\"IMPLICITY_WAIT\")),\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py\", line 94, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webelement.py\", line 404, in _execute\n    return self._parent.execute(command, params)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"/home/ipadula/Copernico/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "attachments": [{"name": "screenshot", "source": "aa1a6b43-c286-43b0-9737-b012d267d530-attachment.png", "type": "image/png"}], "start": 1750275096775, "stop": 1750275124347}, {"name": "And Me dirijo a la seccion \"Economic Groups\"", "status": "skipped", "start": 1750275124402, "stop": 1750275124402}, {"name": "And Presiono el boton \"New\"", "status": "skipped", "start": 1750275124402, "stop": 1750275124402}], "start": 1750275085192, "stop": 1750275124402, "uuid": "bbb1974b-8e9a-45d7-ac91-cce2baf66e9f", "historyId": "ba328313ccdb37b2509a7f15c5feeb03", "fullName": "Risks: Test - Validar la creaci贸n de un grupo econ贸mico", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "economic_group"}, {"name": "tag", "value": "regresion"}, {"name": "tag", "value": "risks"}, {"name": "feature", "value": "Risks"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}